target 'movies' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for movies

pod 'Alamofire'
pod 'Typist'
pod 'PKHUD', '~> 5.0'
pod 'SDWebImage'

target 'moviesTests' do
inherit! :search_paths
# Pods for testing
end

end
